/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iWethSol from "./IWeth.sol";
export type { iWethSol };
export type { IBalancerVault } from "./IBalancerVault";
export type { ICurveFactory } from "./ICurveFactory";
export type { ICurvePool } from "./ICurvePool";
export type { IGenericZaps } from "./IGenericZaps";
export type { ITempleStableRouter } from "./ITempleStableRouter";
export type { IUniswapV2Factory } from "./IUniswapV2Factory";
export type { IUniswapV2Pair } from "./IUniswapV2Pair";
export type { IUniswapV2Router } from "./IUniswapV2Router";
export type { IVault } from "./IVault";
