/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IExitQueue, IExitQueueInterface } from "../IExitQueue";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_exiter",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "join",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IExitQueue__factory {
  static readonly abi = _abi;
  static createInterface(): IExitQueueInterface {
    return new utils.Interface(_abi) as IExitQueueInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IExitQueue {
    return new Contract(address, _abi, signerOrProvider) as IExitQueue;
  }
}
