interface ImportMetaEnv {
  VITE_PUBLIC_STABLE_COIN_ADDRESS: string;
  VITE_PUBLIC_TEMPLE_ADDRESS: string;
  VITE_PUBLIC_LOCKED_OG_TEMPLE_ADDRESS: string;
  VITE_PUBLIC_TEMPLE_STAKING_ADDRESS: string;
  VITE_PUBLIC_PRESALE_ADDRESS: string;
  VITE_PUBLIC_PRESALE_ALLOCATION_ADDRESS: string;
  VITE_PUBLIC_TREASURY_ADDRESS: string;
  VITE_PUBLIC_TREASURY_MANAGEMENT_ADDRESS: string;
  VITE_PUBLIC_EXIT_QUEUE_ADDRESS: string;
  VITE_PUBLIC_VERIFY_QUEST_ADDRESS: string;
  VITE_PUBLIC_OPENING_CEREMONY_ADDRESS: string;
  VITE_PUBLIC_TEMPLE_CASHBACK_ADDRESS: string;
  VITE_PUBLIC_TEMPLE_ROUTER_WHITELIST: string;
  VITE_PUBLIC_TEMPLE_V2_ROUTER_ADDRESS: string;
  VITE_PUBLIC_EXCHANGE_RATE_VALUE: string;
  VITE_PUBLIC_MINT_AND_STAKE_GAS_LIMIT: string;
  VITE_PUBLIC_ECHOING_WHISPERS_ADDRESS: string;
  VITE_ALCHEMY_PROVIDER_NETWORK: string;
  VITE_ALCHEMY_API_KEY: string;
  VITE_SERVER_PRIVATE_KEY: string;
  VITE_ENV: string;
  VITE_PUBLIC_CLAIM_GAS_LIMIT: string;
}
