/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface TempleFraxAMMRouterInterface extends ethers.utils.Interface {
  functions: {
    "addLiquidity(uint256,uint256,uint256,uint256,address,uint256)": FunctionFragment;
    "decayStartBlock()": FunctionFragment;
    "dynamicThresholdDecayPerBlock()": FunctionFragment;
    "dynamicThresholdIncreasePct()": FunctionFragment;
    "dynamicThresholdPrice()": FunctionFragment;
    "fraxToken()": FunctionFragment;
    "getAmountOut(uint256,uint256,uint256)": FunctionFragment;
    "interpolateFromPrice()": FunctionFragment;
    "interpolateToPrice()": FunctionFragment;
    "mintRatioAt(uint256,uint256)": FunctionFragment;
    "pair()": FunctionFragment;
    "quote(uint256,uint256,uint256)": FunctionFragment;
    "removeLiquidity(uint256,uint256,uint256,address,uint256)": FunctionFragment;
    "swapExactFraxForTemple(uint256,uint256,address,uint256)": FunctionFragment;
    "swapExactTempleForFrax(uint256,uint256,address,uint256)": FunctionFragment;
    "templeToken()": FunctionFragment;
    "templeTreasury()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "decayStartBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dynamicThresholdDecayPerBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dynamicThresholdIncreasePct",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dynamicThresholdPrice",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fraxToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAmountOut",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "interpolateFromPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "interpolateToPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintRatioAt",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pair", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "quote",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [BigNumberish, BigNumberish, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactFraxForTemple",
    values: [BigNumberish, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExactTempleForFrax",
    values: [BigNumberish, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "templeToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "templeTreasury",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decayStartBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dynamicThresholdDecayPerBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dynamicThresholdIncreasePct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dynamicThresholdPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fraxToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAmountOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "interpolateFromPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "interpolateToPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintRatioAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pair", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "quote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactFraxForTemple",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapExactTempleForFrax",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "templeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "templeTreasury",
    data: BytesLike
  ): Result;

  events: {};
}

export class TempleFraxAMMRouter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TempleFraxAMMRouterInterface;

  functions: {
    addLiquidity(
      amountADesired: BigNumberish,
      amountBDesired: BigNumberish,
      amountAMin: BigNumberish,
      amountBMin: BigNumberish,
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    decayStartBlock(overrides?: CallOverrides): Promise<[BigNumber]>;

    dynamicThresholdDecayPerBlock(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    dynamicThresholdIncreasePct(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    dynamicThresholdPrice(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { frax: BigNumber; temple: BigNumber }>;

    fraxToken(overrides?: CallOverrides): Promise<[string]>;

    getAmountOut(
      amountIn: BigNumberish,
      reserveIn: BigNumberish,
      reserveOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amountOut: BigNumber }>;

    interpolateFromPrice(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { frax: BigNumber; temple: BigNumber }>;

    interpolateToPrice(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { frax: BigNumber; temple: BigNumber }>;

    mintRatioAt(
      temple: BigNumberish,
      frax: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { numerator: BigNumber; denominator: BigNumber }
    >;

    pair(overrides?: CallOverrides): Promise<[string]>;

    quote(
      amountA: BigNumberish,
      reserveA: BigNumberish,
      reserveB: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amountB: BigNumber }>;

    removeLiquidity(
      liquidity: BigNumberish,
      amountAMin: BigNumberish,
      amountBMin: BigNumberish,
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapExactFraxForTemple(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapExactTempleForFrax(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    templeToken(overrides?: CallOverrides): Promise<[string]>;

    templeTreasury(overrides?: CallOverrides): Promise<[string]>;
  };

  addLiquidity(
    amountADesired: BigNumberish,
    amountBDesired: BigNumberish,
    amountAMin: BigNumberish,
    amountBMin: BigNumberish,
    to: string,
    deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  decayStartBlock(overrides?: CallOverrides): Promise<BigNumber>;

  dynamicThresholdDecayPerBlock(overrides?: CallOverrides): Promise<BigNumber>;

  dynamicThresholdIncreasePct(overrides?: CallOverrides): Promise<BigNumber>;

  dynamicThresholdPrice(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { frax: BigNumber; temple: BigNumber }>;

  fraxToken(overrides?: CallOverrides): Promise<string>;

  getAmountOut(
    amountIn: BigNumberish,
    reserveIn: BigNumberish,
    reserveOut: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  interpolateFromPrice(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { frax: BigNumber; temple: BigNumber }>;

  interpolateToPrice(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { frax: BigNumber; temple: BigNumber }>;

  mintRatioAt(
    temple: BigNumberish,
    frax: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { numerator: BigNumber; denominator: BigNumber }
  >;

  pair(overrides?: CallOverrides): Promise<string>;

  quote(
    amountA: BigNumberish,
    reserveA: BigNumberish,
    reserveB: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  removeLiquidity(
    liquidity: BigNumberish,
    amountAMin: BigNumberish,
    amountBMin: BigNumberish,
    to: string,
    deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapExactFraxForTemple(
    amountIn: BigNumberish,
    amountOutMin: BigNumberish,
    to: string,
    deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapExactTempleForFrax(
    amountIn: BigNumberish,
    amountOutMin: BigNumberish,
    to: string,
    deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  templeToken(overrides?: CallOverrides): Promise<string>;

  templeTreasury(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    addLiquidity(
      amountADesired: BigNumberish,
      amountBDesired: BigNumberish,
      amountAMin: BigNumberish,
      amountBMin: BigNumberish,
      to: string,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        amountA: BigNumber;
        amountB: BigNumber;
        liquidity: BigNumber;
      }
    >;

    decayStartBlock(overrides?: CallOverrides): Promise<BigNumber>;

    dynamicThresholdDecayPerBlock(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    dynamicThresholdIncreasePct(overrides?: CallOverrides): Promise<BigNumber>;

    dynamicThresholdPrice(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { frax: BigNumber; temple: BigNumber }>;

    fraxToken(overrides?: CallOverrides): Promise<string>;

    getAmountOut(
      amountIn: BigNumberish,
      reserveIn: BigNumberish,
      reserveOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    interpolateFromPrice(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { frax: BigNumber; temple: BigNumber }>;

    interpolateToPrice(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { frax: BigNumber; temple: BigNumber }>;

    mintRatioAt(
      temple: BigNumberish,
      frax: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { numerator: BigNumber; denominator: BigNumber }
    >;

    pair(overrides?: CallOverrides): Promise<string>;

    quote(
      amountA: BigNumberish,
      reserveA: BigNumberish,
      reserveB: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeLiquidity(
      liquidity: BigNumberish,
      amountAMin: BigNumberish,
      amountBMin: BigNumberish,
      to: string,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { amountA: BigNumber; amountB: BigNumber }
    >;

    swapExactFraxForTemple(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      to: string,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapExactTempleForFrax(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      to: string,
      deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    templeToken(overrides?: CallOverrides): Promise<string>;

    templeTreasury(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    addLiquidity(
      amountADesired: BigNumberish,
      amountBDesired: BigNumberish,
      amountAMin: BigNumberish,
      amountBMin: BigNumberish,
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    decayStartBlock(overrides?: CallOverrides): Promise<BigNumber>;

    dynamicThresholdDecayPerBlock(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    dynamicThresholdIncreasePct(overrides?: CallOverrides): Promise<BigNumber>;

    dynamicThresholdPrice(overrides?: CallOverrides): Promise<BigNumber>;

    fraxToken(overrides?: CallOverrides): Promise<BigNumber>;

    getAmountOut(
      amountIn: BigNumberish,
      reserveIn: BigNumberish,
      reserveOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    interpolateFromPrice(overrides?: CallOverrides): Promise<BigNumber>;

    interpolateToPrice(overrides?: CallOverrides): Promise<BigNumber>;

    mintRatioAt(
      temple: BigNumberish,
      frax: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pair(overrides?: CallOverrides): Promise<BigNumber>;

    quote(
      amountA: BigNumberish,
      reserveA: BigNumberish,
      reserveB: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeLiquidity(
      liquidity: BigNumberish,
      amountAMin: BigNumberish,
      amountBMin: BigNumberish,
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapExactFraxForTemple(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapExactTempleForFrax(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    templeToken(overrides?: CallOverrides): Promise<BigNumber>;

    templeTreasury(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addLiquidity(
      amountADesired: BigNumberish,
      amountBDesired: BigNumberish,
      amountAMin: BigNumberish,
      amountBMin: BigNumberish,
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    decayStartBlock(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    dynamicThresholdDecayPerBlock(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    dynamicThresholdIncreasePct(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    dynamicThresholdPrice(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fraxToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAmountOut(
      amountIn: BigNumberish,
      reserveIn: BigNumberish,
      reserveOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    interpolateFromPrice(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    interpolateToPrice(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mintRatioAt(
      temple: BigNumberish,
      frax: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pair(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    quote(
      amountA: BigNumberish,
      reserveA: BigNumberish,
      reserveB: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeLiquidity(
      liquidity: BigNumberish,
      amountAMin: BigNumberish,
      amountBMin: BigNumberish,
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapExactFraxForTemple(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapExactTempleForFrax(
      amountIn: BigNumberish,
      amountOutMin: BigNumberish,
      to: string,
      deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    templeToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    templeTreasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
