const ENV_VARS = import.meta.env;

export enum TEAM_PAYMENTS_TYPES {
  FIXED,
  CONTINGENT,
}

export enum TEAM_PAYMENTS_EPOCHS {
  R1 = 0,
  R2 = 1,
}

export const TEAM_PAYMENTS_FIXED_ADDRESSES_BY_EPOCH = {
  [TEAM_PAYMENTS_EPOCHS.R1]:
    ENV_VARS.VITE_PUBLIC_TEMPLE_R1_TEAM_FIXED_PAYMENTS_ADDRESS,
  [TEAM_PAYMENTS_EPOCHS.R2]:
    ENV_VARS.VITE_PUBLIC_TEMPLE_R2_TEAM_FIXED_PAYMENTS_ADDRESS,
};

export const TEAM_PAYMENTS_CONTINGENT_ADDRESSES_BY_EPOCH = {
  [TEAM_PAYMENTS_EPOCHS.R1]:
    ENV_VARS.VITE_PUBLIC_TEMPLE_R1_TEAM_CONTINGENT_PAYMENTS_ADDRESS,
  [TEAM_PAYMENTS_EPOCHS.R2]:
    ENV_VARS.VITE_PUBLIC_TEMPLE_R2_TEAM_CONTINGENT_PAYMENTS_ADDRESS,
};
