export enum TICKER_SYMBOL {
  STABLE_TOKEN = 'FRAX',
  TEMPLE_TOKEN = 'TEMPLE',
  OG_TEMPLE_TOKEN = 'OGTEMPLE',
  TEMPLE_GOLD_TOKEN = 'TGLD',
  FRAX = 'FRAX',
  ETH = 'ETH',
  USDC = 'USDC',
  USDT = 'USDT',
  USDS = 'USDS',
  DAI = 'DAI',
  WETH = 'WETH',
  OHM = 'OHM',
}
