const ENV_VARS = import.meta.env;

const STABLE_COIN_ADDRESS = ENV_VARS.VITE_PUBLIC_STABLE_COIN_ADDRESS;
const TEMPLE_ADDRESS = ENV_VARS.VITE_PUBLIC_TEMPLE_ADDRESS;
const LOCKED_OG_TEMPLE_ADDRESS = ENV_VARS.VITE_PUBLIC_LOCKED_OG_TEMPLE_ADDRESS;
const LOCKED_OG_TEMPLE_DEVOTION_ADDRESS =
  ENV_VARS.VITE_PUBLIC_LOCKED_OG_TEMPLE_DEVOTION_ADDRESS;
const TEMPLE_STAKING_ADDRESS = ENV_VARS.VITE_PUBLIC_TEMPLE_STAKING_ADDRESS;
const TREASURY_ADDRESS = ENV_VARS.VITE_PUBLIC_TREASURY_ADDRESS;
const EXIT_QUEUE_ADDRESS = ENV_VARS.VITE_PUBLIC_EXIT_QUEUE_ADDRESS;
const OPENING_CEREMONY_ADDRESS = ENV_VARS.VITE_PUBLIC_OPENING_CEREMONY_ADDRESS;
const TEMPLE_CASHBACK_ADDRESS = ENV_VARS.VITE_PUBLIC_TEMPLE_CASHBACK_ADDRESS;
const AMM_WHITELIST_ADDRESS = ENV_VARS.VITE_PUBLIC_TEMPLE_ROUTER_WHITELIST;
const TEMPLE_V2_ROUTER_ADDRESS = ENV_VARS.VITE_PUBLIC_TEMPLE_V2_ROUTER_ADDRESS;
const TEMPLE_V2_PAIR_ADDRESS = ENV_VARS.VITE_PUBLIC_TEMPLE_V2_PAIR_ADDRESS;
const ACCELERATED_EXIT_QUEUE_ADDRESS =
  ENV_VARS.VITE_PUBLIC_ACCELERATED_EXIT_QUEUE_ADDRESS;
const FAITH_AIRDROP_ADDRESS = ENV_VARS.VITE_PUBLIC_FAITH_AIRDROP_ADDRESS;

const TEMPLE_TEAM_FIXED_PAYMENTS_ADDRESS =
  ENV_VARS.VITE_PUBLIC_TEMPLE_R1_TEAM_FIXED_PAYMENTS_ADDRESS;
const TEMPLE_TEAM_CONTINGENT_PAYMENTS_ADDRESS =
  ENV_VARS.VITE_PUBLIC_TEMPLE_R1_TEAM_CONTINGENT_PAYMENTS_ADDRESS;
const TEMPLE_DEVOTION_ADDRESS = ENV_VARS.VITE_PUBLIC_TEMPLE_DEVOTION_ADDRESS;
const TEMPLE_FAITH_ADDRESS = ENV_VARS.VITE_PUBLIC_TEMPLE_FAITH_ADDRESS;
if (
  STABLE_COIN_ADDRESS === undefined ||
  TEMPLE_ADDRESS === undefined ||
  TEMPLE_STAKING_ADDRESS === undefined ||
  TREASURY_ADDRESS === undefined ||
  LOCKED_OG_TEMPLE_ADDRESS === undefined ||
  EXIT_QUEUE_ADDRESS === undefined ||
  OPENING_CEREMONY_ADDRESS === undefined ||
  TEMPLE_CASHBACK_ADDRESS === undefined ||
  TEMPLE_V2_ROUTER_ADDRESS === undefined ||
  TEMPLE_V2_PAIR_ADDRESS === undefined ||
  ACCELERATED_EXIT_QUEUE_ADDRESS === undefined ||
  FAITH_AIRDROP_ADDRESS === undefined ||
  TEMPLE_DEVOTION_ADDRESS === undefined ||
  TEMPLE_FAITH_ADDRESS === undefined ||
  LOCKED_OG_TEMPLE_DEVOTION_ADDRESS === undefined
) {
  console.info(`
STABLE_COIN_ADDRESS=${STABLE_COIN_ADDRESS}
TEMPLE_ADDRESS=${TEMPLE_ADDRESS}
TEMPLE_STAKING_ADDRESS=${TEMPLE_STAKING_ADDRESS}
TREASURY_ADDRESS=${TREASURY_ADDRESS}
LOCKED_OG_TEMPLE_ADDRESS=${LOCKED_OG_TEMPLE_ADDRESS}
EXIT_QUEUE_ADDRESS=${EXIT_QUEUE_ADDRESS}
OPENING_CEREMONY_ADDRESS=${OPENING_CEREMONY_ADDRESS}
TEMPLE_CASHBACK_ADDRESS=${TEMPLE_CASHBACK_ADDRESS}
TEMPLE_V2_ROUTER_ADDRESS=${TEMPLE_V2_ROUTER_ADDRESS}
TEMPLE_V2_PAIR_ADDRESS=${TEMPLE_V2_PAIR_ADDRESS}
ACCELERATED_EXIT_QUEUE_ADDRESS=${ACCELERATED_EXIT_QUEUE_ADDRESS}
FAITH_AIRDROP_ADDRESS=${FAITH_AIRDROP_ADDRESS}
TEMPLE_DEVOTION_ADDRESS=${TEMPLE_DEVOTION_ADDRESS}
LOCKED_OG_TEMPLE_DEVOTION_ADDRESS=${LOCKED_OG_TEMPLE_DEVOTION_ADDRESS}
TEMPLE_FAITH_ADDRESS=${TEMPLE_FAITH_ADDRESS}
`);
  throw new Error(`Missing contract address from .env`);
}
