const ENV_VARS = import.meta.env;

export const FRAX_ADDRESS = ENV_VARS.VITE_PUBLIC_STABLE_COIN_ADDRESS;
export const FEI_ADDRESS = ENV_VARS.VITE_PUBLIC_FEI_ADDRESS;
export const TEMPLE_ADDRESS = ENV_VARS.VITE_PUBLIC_TEMPLE_ADDRESS;
export const LOCKED_OG_TEMPLE_ADDRESS = ENV_VARS.VITE_PUBLIC_LOCKED_OG_TEMPLE_ADDRESS;
export const LOCKED_OG_TEMPLE_DEVOTION_ADDRESS = ENV_VARS.VITE_PUBLIC_LOCKED_OG_TEMPLE_DEVOTION_ADDRESS;
export const TEMPLE_STAKING_ADDRESS = ENV_VARS.VITE_PUBLIC_TEMPLE_STAKING_ADDRESS;
export const TREASURY_ADDRESS = ENV_VARS.VITE_PUBLIC_TREASURY_ADDRESS;
export const EXIT_QUEUE_ADDRESS = ENV_VARS.VITE_PUBLIC_EXIT_QUEUE_ADDRESS;
export const TEMPLE_CASHBACK_ADDRESS = ENV_VARS.VITE_PUBLIC_TEMPLE_CASHBACK_ADDRESS;
export const AMM_WHITELIST_ADDRESS = ENV_VARS.VITE_PUBLIC_TEMPLE_ROUTER_WHITELIST;
export const TEMPLE_V2_ROUTER_ADDRESS = ENV_VARS.VITE_PUBLIC_TEMPLE_V2_ROUTER_ADDRESS;
export const TEMPLE_V2_FRAX_PAIR_ADDRESS = ENV_VARS.VITE_PUBLIC_TEMPLE_V2_PAIR_ADDRESS;
export const TEMPLE_V2_FEI_PAIR_ADDRESS = ENV_VARS.VITE_PUBLIC_TEMPLE_V2_FEI_PAIR;
export const ACCELERATED_EXIT_QUEUE_ADDRESS = ENV_VARS.VITE_PUBLIC_ACCELERATED_EXIT_QUEUE_ADDRESS;
export const FAITH_AIRDROP_ADDRESS = ENV_VARS.VITE_PUBLIC_FAITH_AIRDROP_ADDRESS;
export const TEMPLE_RELIC_ADDRESS = ENV_VARS.VITE_PUBLIC_TEMPLE_RELIC_ADDRESS;
export const TEMPLE_RELIC_ITEMS_ADDRESS = ENV_VARS.VITE_PUBLIC_TEMPLE_RELIC_ITEMS_ADDRESS;

export const TEMPLE_TEAM_FIXED_PAYMENTS_ADDRESS = ENV_VARS.VITE_PUBLIC_TEMPLE_R1_TEAM_FIXED_PAYMENTS_ADDRESS;
export const TEMPLE_TEAM_CONTINGENT_PAYMENTS_ADDRESS = ENV_VARS.VITE_PUBLIC_TEMPLE_R1_TEAM_CONTINGENT_PAYMENTS_ADDRESS;
export const TEMPLE_DEVOTION_ADDRESS = ENV_VARS.VITE_PUBLIC_TEMPLE_DEVOTION_ADDRESS;
export const TEMPLE_FAITH_ADDRESS = ENV_VARS.VITE_PUBLIC_TEMPLE_FAITH_ADDRESS;
export const TEMPLE_IV_SWAP_ADDRESS = ENV_VARS.VITE_PUBLIC_TEMPLE_IV_SWAP_ADDRESS;
export const FRAX_SELL_DISABLED_IV_MULTIPLE = ENV_VARS.VITE_PUBLIC_FRAX_SELL_DISABLED_IV_MULTIPLE;
//TODO: remove VITE_PUBLIC prefix from exported vars
export const NEXT_PUBLIC_EXCHANGE_RATE_VALUE = ENV_VARS.NEXT_PUBLIC_EXCHANGE_RATE_VALUE;
export const VITE_PUBLIC_MINT_AND_STAKE_GAS_LIMIT = ENV_VARS.VITE_PUBLIC_MINT_AND_STAKE_GAS_LIMIT;
export const VITE_PUBLIC_TEMPLE_STAKING_UNSTAKE_BASE_GAS_LIMIT =
  ENV_VARS.VITE_PUBLIC_TEMPLE_STAKING_UNSTAKE_BASE_GAS_LIMIT;
export const VITE_PUBLIC_TEMPLE_STAKING_UNSTAKE_PER_EPOCH_GAS_LIMIT =
  ENV_VARS.VITE_PUBLIC_TEMPLE_STAKING_UNSTAKE_PER_EPOCH_GAS_LIMIT;
export const VITE_PUBLIC_CLAIM_GAS_LIMIT = ENV_VARS.VITE_PUBLIC_CLAIM_GAS_LIMIT;
export const VITE_PUBLIC_CLAIM_FAITH_GAS_LIMIT = ENV_VARS.VITE_PUBLIC_CLAIM_FAITH_GAS_LIMIT;
export const VITE_PUBLIC_WITHDRAW_EPOCHS_BASE_GAS_LIMIT = ENV_VARS.VITE_PUBLIC_WITHDRAW_EPOCHS_BASE_GAS_LIMIT;
export const VITE_PUBLIC_WITHDRAW_EPOCHS_PER_EPOCH_GAS_LIMIT = ENV_VARS.VITE_PUBLIC_WITHDRAW_EPOCHS_PER_EPOCH_GAS_LIMIT;
export const VITE_PUBLIC_RESTAKE_EPOCHS_BASE_GAS_LIMIT = ENV_VARS.VITE_PUBLIC_RESTAKE_EPOCHS_BASE_GAS_LIMIT;
export const VITE_PUBLIC_RESTAKE_EPOCHS_PER_EPOCH_GAS_LIMIT = ENV_VARS.VITE_PUBLIC_RESTAKE_EPOCHS_PER_EPOCH_GAS_LIMIT;
export const VITE_PUBLIC_AMM_FRAX_FOR_TEMPLE_GAS_LIMIT = ENV_VARS.VITE_PUBLIC_AMM_FRAX_FOR_TEMPLE_GAS_LIMIT;
export const VITE_PUBLIC_AMM_TEMPLE_FOR_FRAX_GAS_LIMIT = ENV_VARS.VITE_PUBLIC_AMM_TEMPLE_FOR_FRAX_GAS_LIMIT;
export const VITE_PUBLIC_CLAIM_OGTEMPLE_GAS_LIMIT = ENV_VARS.VITE_PUBLIC_CLAIM_OGTEMPLE_GAS_LIMIT;
export const VITE_PUBLIC_STAKE_GAS_LIMIT = ENV_VARS.VITE_PUBLIC_STAKE_GAS_LIMIT;
export const VITE_PUBLIC_DEVOTION_LOCK_AND_VERIFY_GAS_LIMIT = ENV_VARS.VITE_PUBLIC_DEVOTION_LOCK_AND_VERIFY_GAS_LIMIT;

if (
  FRAX_ADDRESS === undefined ||
  FEI_ADDRESS === undefined ||
  TEMPLE_ADDRESS === undefined ||
  TEMPLE_STAKING_ADDRESS === undefined ||
  TREASURY_ADDRESS === undefined ||
  LOCKED_OG_TEMPLE_ADDRESS === undefined ||
  EXIT_QUEUE_ADDRESS === undefined ||
  TEMPLE_CASHBACK_ADDRESS === undefined ||
  TEMPLE_V2_ROUTER_ADDRESS === undefined ||
  TEMPLE_V2_FRAX_PAIR_ADDRESS === undefined ||
  ACCELERATED_EXIT_QUEUE_ADDRESS === undefined ||
  FAITH_AIRDROP_ADDRESS === undefined ||
  TEMPLE_DEVOTION_ADDRESS === undefined ||
  TEMPLE_FAITH_ADDRESS === undefined ||
  LOCKED_OG_TEMPLE_DEVOTION_ADDRESS === undefined
) {
  console.info(`
FRAX_ADDRESS=${FRAX_ADDRESS}
FEI_ADDRESS=${FEI_ADDRESS}
TEMPLE_ADDRESS=${TEMPLE_ADDRESS}
TEMPLE_STAKING_ADDRESS=${TEMPLE_STAKING_ADDRESS}
TREASURY_ADDRESS=${TREASURY_ADDRESS}
LOCKED_OG_TEMPLE_ADDRESS=${LOCKED_OG_TEMPLE_ADDRESS}
EXIT_QUEUE_ADDRESS=${EXIT_QUEUE_ADDRESS}
TEMPLE_CASHBACK_ADDRESS=${TEMPLE_CASHBACK_ADDRESS}
TEMPLE_V2_ROUTER_ADDRESS=${TEMPLE_V2_ROUTER_ADDRESS}
TEMPLE_V2_FRAX_PAIR_ADDRESS=${TEMPLE_V2_FRAX_PAIR_ADDRESS}
TEMPLE_V2_FEI_PAIR_ADDRESS=${TEMPLE_V2_FEI_PAIR_ADDRESS}
ACCELERATED_EXIT_QUEUE_ADDRESS=${ACCELERATED_EXIT_QUEUE_ADDRESS}
FAITH_AIRDROP_ADDRESS=${FAITH_AIRDROP_ADDRESS}
TEMPLE_DEVOTION_ADDRESS=${TEMPLE_DEVOTION_ADDRESS}
LOCKED_OG_TEMPLE_DEVOTION_ADDRESS=${LOCKED_OG_TEMPLE_DEVOTION_ADDRESS}
TEMPLE_FAITH_ADDRESS=${TEMPLE_FAITH_ADDRESS}
`);
  throw new Error(`Missing contract address from .env`);
}
