name: dapp => stage
on:
  push:
    branches:    
      - 'stage'
    paths:
      - "apps/dapp/**"
      - ".github/workflows/prod-dapp-main.yaml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '--prod -A apps/dapp/vercel.json' #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.DAPP_PROJECT_ID}} #Required 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alias-domains: | #Optional
            staging.temple.start.dev