name: dapp => prod
on:
  push:
    branches:
      - 'main'
    paths:
      - "apps/dapp/**"
      - ".github/workflows/dapp-prod.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.DAPP_PROJECT_ID }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: '24'
      - name: Install Dependencies
        run: yarn install
        working-directory: apps/dapp
      - name: Deploy to Vercel
        id: deploy_step
        run: bash .github/scripts/vercel-deploy.sh production templedao.link --prod
        continue-on-error: true
      - name: "notify failure"
        if: steps.deploy_step.outcome == 'failure'
        uses: rjstone/discord-webhook-notify@1399c1b2d57cc05894d506d2cfdc33c5f012b993
        with:
          severity: error
          description: (Dapp) PROD Deploy to Vercel failed!
          details: Check the GH Action or Vercel logs for details.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
      - name: "fail"
        if: steps.deploy_step.outcome == 'failure'
        run: exit 1
      - name: "notify success"
        uses: rjstone/discord-webhook-notify@1399c1b2d57cc05894d506d2cfdc33c5f012b993
        with:
          severity: info
          description: (Dapp) PROD Deploy to Vercel succeeded!
          details: "[View Prod Deployment](https://templedao.link)"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
