name: dapp pr
on:
  pull_request:
    paths:
      - "apps/dapp/**"
      - ".github/workflows/pr-dapp-main.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '--prod -A apps/dapp/vercel.json' #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.DAPP_PROJECT_ID}} #Required 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alias-domains: | #Optional
            pr-{{PR_NUMBER}}.staging.temple.start.dev