name: dapp => prod
on:
  push:
    branches:    
      - 'main'
    paths:
      - "apps/dapp/**"
      - ".github/workflows/dapp-prod.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        id: deploy_step
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '--prod -A apps/dapp/vercel.json' #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  #Required
          vercel-project-id: ${{ secrets.DAPP_PROJECT_ID }} #Required 
          github-token: ${{ secrets.CI_TOKEN }}
          github-comment: false
          scope: ${{ secrets.VERCEL_ORG_ID }}
          alias-domains: | #Optional
            templedao.link
        continue-on-error: true
      - name: "notify failure"
        if: steps.deploy_step.outcome == 'failure'
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          description: (Dapp) PROD Deploy to Vercel failed!
          details: Check the GH Action or Vercel logs for details.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
      - name: "fail"
        if: steps.deploy_step.outcome == 'failure'
        run: exit 1
      - name: "notify success"
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          description: (Dapp) PROD Deploy to Vercel succeeded!
          details: "[View Prod Deployment](https://templedao.link)"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}