# We manually setup and run slither here, as the prebaked github action
# (at https://github.com/crytic/slither-action)
# fails with permission errors inside the docker container for this project

name: Slither Analysis
on:
  push:
    paths:
      - "protocol/**"
      - ".github/workflows/slither.yaml"
jobs:
  analyze:
    # if: ${{ false }} # Slither has an issue with prb math, and is super slow...
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'
          cache-dependency-path: protocol/yarn.lock

      - run: yarn install
        working-directory: protocol
  
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.0.10
        with:
          cache: true
        #with:
        #  version: nightly-ca67d15f4abd46394b324c50e21e66f306a1162d
      
      - run: forge --version
        working-directory: protocol

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
          cache-dependency-path: protocol/slither.requirements.txt
    
      - name: install slither
        run: cd protocol && pip install -r slither.requirements.txt      
      
      - name: run slither
        run: cd protocol && yarn slither-check
