name: Sync Typechain Directories
on:
  pull_request:
    branches:
      - 'stage'
      - 'core'
    types: 
      - closed
    paths:
      - 'protocol/contracts/**'

jobs:
  align_typechain_dir:
    name: Sync Typechain Directories
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: '20'
          cache: 'yarn'
      - name : Yarn Commands
        run: |
          yarn install
          yarn compile
        working-directory: protocol
      - name : Sync Directories
        run : |
          rsync -avzh ./protocol/typechain ./apps/dapp/src/types/
      - name: Setting up git 
        run : |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Pushing Automated Commit
        run: |
          git add ./apps/dapp/src/types/
          git commit -m "Automated Action: Update Dapp Typechain Types"
          git push
